FROM n8nio/n8n:latest

ENV N8N_PORT=5678
ENV NODE_ENV=production
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_METRICS_ENABLED=false
ENV N8N_HIRING_BANNER_ENABLED=false
ENV WEBHOOK_URL=https://${RAILWAY_STATIC_URL}
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=${PGHOST}
ENV DB_POSTGRESDB_PORT=${PGPORT}
ENV DB_POSTGRESDB_DATABASE=${PGDATABASE}
ENV DB_POSTGRESDB_USER=${PGUSER}
ENV DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
ENV N8N_HOST=${RAILWAY_STATIC_URL}
ENV GENERIC_TIMEZONE=UTC

EXPOSE 5678
